const api=(location.protocol==='file:'||location.hostname.endsWith('github.io'))?'https://api.jikan.moe/v4':`${location.origin}/api`,grid=document.querySelector('#animeGrid'),empty=document.querySelector('#emptyState'),input=document.querySelector('#searchInput'),status=document.querySelector('#catalogStatus'),scheduleList=document.querySelector('#scheduleList');let activeGenre='all',debounceId;
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const watchUrl=title=>`https://www.justwatch.com/us/search?q=${encodeURIComponent(title)}`;
function card(anime){const title=anime.title_english||anime.title||'Untitled',genres=(anime.genres||[]).slice(0,2).map(g=>g.name).join(' · ')||'Anime',image=anime.images?.jpg?.large_image_url||anime.images?.jpg?.image_url,style=image?`--poster:linear-gradient(0deg,rgba(17,31,35,.65),rgba(17,31,35,.04)),url('${image}')`:'--poster:linear-gradient(145deg,#315d68,#e2ad6a)',score=anime.score?`★ ${anime.score.toFixed(1)}`:'New';return `<article class="anime-card"><div class="poster" style="${style}"><div class="poster-title">${esc(title)}</div><div class="watch-overlay"><a class="watch-link" href="${watchUrl(title)}" target="_blank" rel="noreferrer">Check availability ↗</a></div></div><div class="tags"><span>${esc(genres)} · ${anime.year||'—'}</span><span class="score">${score}</span></div></article>`}
async function loadCatalog(){const query=input.value.trim(),params=new URLSearchParams({limit:'12',sfw:'true'});let endpoint=`${api}/top/anime?${params}`;if(query||activeGenre!=='all'){if(query)params.set('q',query);if(activeGenre!=='all')params.set('genres',activeGenre);params.set('order_by',query?'popularity':'score');params.set('sort','desc');endpoint=`${api}/anime?${params}`}status.hidden=false;status.textContent='Loading the live catalog…';grid.setAttribute('aria-busy','true');try{const response=await fetch(endpoint);if(!response.ok)throw new Error('Catalog request failed');const {data=[]}=await response.json();grid.innerHTML=data.map(card).join('');empty.hidden=data.length>0;status.textContent=data.length?`Showing ${data.length} live results from MyAnimeList data.`:'';document.querySelector('#catalogCount').textContent=`${data.length}+`}catch{grid.innerHTML='';empty.hidden=false;status.textContent='The live catalog is temporarily unavailable. Please check your connection and try again.'}finally{grid.removeAttribute('aria-busy')}}
function currentDay(){return new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date()).toLowerCase()}
async function loadSchedule(){try{const response=await fetch(`${api}/schedules?filter=${currentDay()}&limit=3&sfw=true`);if(!response.ok)throw new Error();const {data=[]}=await response.json();scheduleList.innerHTML=data.slice(0,3).map((anime,index)=>{const day=['TODAY','NEXT','UP'][index],title=anime.title_english||anime.title,episode=anime.broadcast?.string||'Schedule details vary by region';return `<article><span class="day">${day}<br /><b>${String(index+1).padStart(2,'0')}</b></span><div><h3>${esc(title)}</h3><p>${esc(episode)}</p></div><button class="remind" data-title="${esc(title)}">Remind me</button></article>`}).join('')||'<p class="catalog-status">No schedule entries are available today.</p>'}catch{scheduleList.innerHTML='<p class="catalog-status">The live schedule is temporarily unavailable.</p>'}}
document.querySelector('#filters').addEventListener('click',event=>{if(!event.target.matches('button'))return;activeGenre=event.target.dataset.filter;document.querySelectorAll('#filters button').forEach(button=>button.classList.toggle('active',button===event.target));loadCatalog()});input.addEventListener('input',()=>{clearTimeout(debounceId);debounceId=setTimeout(loadCatalog,450)});document.querySelector('#showAll').onclick=()=>{activeGenre='all';input.value='';document.querySelectorAll('#filters button').forEach((button,i)=>button.classList.toggle('active',i===0));loadCatalog();grid.scrollIntoView({behavior:'smooth',block:'center'})};
const dialog=document.querySelector('#modal');document.querySelector('#howItWorks').onclick=()=>dialog.showModal();document.querySelector('.modal-close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});document.querySelector('#themeButton').onclick=()=>document.body.classList.toggle('dark');const toast=document.querySelector('#toast');document.addEventListener('click',event=>{if(!event.target.matches('.remind'))return;toast.textContent=`Reminder saved for ${event.target.dataset.title}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)});loadCatalog();loadSchedule();

